# -*- coding: utf-8 -*-
"""480_OOP_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XT48R3VcVdQCXmc0DxE2AA4tTv8eSFll
"""

class Book:

    def __init__(self, title, author, num_pages, ISBN, publisher):
        self.title = title
        self.author = author
        self._num_pages = num_pages
        self._ISBN = ISBN
        self._publisher = publisher

#my_book = Book("Mockingbird", "Jim", 250, 5123161, "Clearhouse")

#print(my_book.ISBN)